# Scalar

In [14]:
import numpy as np

In [16]:
X = np.array(10)
y = np.array(200)

In [19]:
y.ndim

0

# 1D Tensor

In [20]:
x = np.array([10,20,30,40])

In [21]:
print(x)

[10 20 30 40]


In [22]:
x.ndim

1

In [24]:
table = np.array([[1,3,4],[4,5,6],[7,8,9]])

In [26]:
table

array([[1, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
table.ndim

2

# 3D tensor

In [28]:
ddd = np.array([[[10,20],[100,200]],[[10,20],[100,200]],[[10,20],[100,200]]])

In [29]:
ddd

array([[[ 10,  20],
        [100, 200]],

       [[ 10,  20],
        [100, 200]],

       [[ 10,  20],
        [100, 200]]])

In [30]:
ddd.ndim

3